### ISSUE TITLE
About torch-radon

### ISSUE THREAD

**Issue by huololo** [YC-Markus/code-for-DDDM#1]
Is the import torch_radon in reco_train.py the torch-radon on github?
Here is torch_radon's URL：

https://github.com/matteo-ronchetti/torch-radon

**Comment by YC-Markus** [comment]
Yes. As some minor changes in torch_radon are required, I recommend to follow the guidance in helix2fan. URL: https://github.com/faebstn96/helix2fan

**Comment by huololo** [comment]
> 是的。由于需要对torch_radon进行一些细微的更改，因此我建议遵循 helix2fan 中的指导。网址： https://github.com/faebstn96/helix2fan

Thank you for your answer.
